---
# Source: ip-country-lookup/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: urumia-ac-ip-country-lookup
  labels:
    app.kubernetes.io/name: ip-country-lookup
    app.kubernetes.io/instance: urumia-ac
    app.kubernetes.io/version: "0.1.0"
data:
  DATABASE_URL: "cG9zdGdyZXNxbDovL2FwcDpwYXNzd29yZEBpcC1jb3VudHJ5LWRiLXJ3LnVydW1pYS1hYy1kZW1vLnN2Yy9hcHA="
