name: Build Docker Image

on:
  push:
    paths:
      - 'app/ip-country-lookup/src/**/*'
      - 'app/ip-country-lookup/requirements.txt'
      - 'app/ip-country-lookup/Dockerfile'
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.sha.outputs.SHORT_SHA }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Get short SHA
        id: sha
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT
        
      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          registry: registry-9599bb66cc-k3s-stg.apps.ir-central1.arvancaas.ir
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app/ip-country-lookup
          file: ./app/ip-country-lookup/Dockerfile
          push: true
          tags: |
            registry-9599bb66cc-k3s-stg.apps.ir-central1.arvancaas.ir/ip-country:${{ steps.sha.outputs.SHORT_SHA }}
            registry-9599bb66cc-k3s-stg.apps.ir-central1.arvancaas.ir/ip-country:latest
      
      - name: Trigger deploy workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: image-built
          client-payload: '{"image_tag": "${{ steps.sha.outputs.SHORT_SHA }}"}'
